package com.alphasystem.app.morphologicalengine.conjugation.transformer.noun.factory;

import org.springframework.beans.factory.annotation.Qualifier;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * @author sali
 */
@Target({ElementType.FIELD, ElementType.METHOD, ElementType.TYPE, ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
@Qualifier
public @interface TransformerFactory {

    TransformerFactoryType value();

    enum TransformerFactoryType {
        FORM_I_MASCULINE_ACTIVE_PARTICIPLE, FORM_I_MASCULINE_PASSIVE_PARTICIPLE, FORM_I_CATEGORY_U_MASCULINE_ACTIVE_PARTICIPLE,
        FORM_II_MASCULINE_ACTIVE_PARTICIPLE, FORM_II_MASCULINE_PASSIVE_PARTICIPLE, FORM_III_MASCULINE_ACTIVE_PARTICIPLE,
        FORM_III_MASCULINE_PASSIVE_PARTICIPLE, FORM_IV_MASCULINE_ACTIVE_PARTICIPLE, FORM_IV_MASCULINE_PASSIVE_PARTICIPLE,
        FORM_V_MASCULINE_ACTIVE_PARTICIPLE, FORM_V_MASCULINE_PASSIVE_PARTICIPLE, FORM_VI_MASCULINE_ACTIVE_PARTICIPLE,
        FORM_VII_MASCULINE_PASSIVE_PARTICIPLE, FORM_VIII_MASCULINE_ACTIVE_PARTICIPLE, FORM_VIII_MASCULINE_PASSIVE_PARTICIPLE,
        FORM_IX_MASCULINE_ACTIVE_PARTICIPLE, FORM_X_MASCULINE_ACTIVE_PARTICIPLE, FORM_X_MASCULINE_PASSIVE_PARTICIPLE,
        FORM_I_FEMININE_ACTIVE_PARTICIPLE, FORM_I_FEMININE_PASSIVE_PARTICIPLE, FORM_I_CATEGORY_U_FEMININE_ACTIVE_PARTICIPLE,
        FORM_II_FEMININE_ACTIVE_PARTICIPLE, FORM_II_FEMININE_PASSIVE_PARTICIPLE, FORM_III_FEMININE_ACTIVE_PARTICIPLE,
        FORM_III_FEMININE_PASSIVE_PARTICIPLE, FORM_IV_FEMININE_ACTIVE_PARTICIPLE, FORM_IV_FEMININE_PASSIVE_PARTICIPLE,
        FORM_V_FEMININE_ACTIVE_PARTICIPLE, FORM_V_FEMININE_PASSIVE_PARTICIPLE, FORM_VI_FEMININE_ACTIVE_PARTICIPLE,
        FORM_VI_FEMININE_PASSIVE_PARTICIPLE, FORM_VII_FEMININE_ACTIVE_PARTICIPLE, FORM_VII_FEMININE_PASSIVE_PARTICIPLE,
        FORM_VIII_FEMININE_ACTIVE_PARTICIPLE, FORM_VIII_FEMININE_PASSIVE_PARTICIPLE, FORM_IX_FEMININE_ACTIVE_PARTICIPLE,
        FORM_X_FEMININE_ACTIVE_PARTICIPLE, FORM_X_FEMININE_PASSIVE_PARTICIPLE, FORM_VI_MASCULINE_PASSIVE_PARTICIPLE,
        VERBAL_NOUN_V1, VERBAL_NOUN_V2, VERBAL_NOUN_V3, VERBAL_NOUN_V4, VERBAL_NOUN_V5, VERBAL_NOUN_V6, VERBAL_NOUN_V7,
        VERBAL_NOUN_V8, VERBAL_NOUN_V9, VERBAL_NOUN_V10, VERBAL_NOUN_V11, VERBAL_NOUN_V12, VERBAL_NOUN_V13, VERBAL_NOUN_V14,
        VERBAL_NOUN_V15, VERBAL_NOUN_V27, VERBAL_NOUN_V28, VERBAL_NOUN_FORM_II, VERBAL_NOUN_FORM_III_V1, VERBAL_NOUN_FORM_III_V2,
        VERBAL_NOUN_FORM_IV, VERBAL_NOUN_FORM_V, VERBAL_NOUN_FORM_VI, VERBAL_NOUN_FORM_VII, VERBAL_NOUN_FORM_VIII,
        VERBAL_NOUN_FORM_IX, VERBAL_NOUN_FORM_X, NOUN_OF_PLACE_AND_TIME_V1, NOUN_OF_PLACE_AND_TIME_V2, NOUN_OF_PLACE_AND_TIME_V3
    }

}
