package com.alphasystem.app.morphologicalengine.conjugation.model;

import com.alphasystem.morphologicalanalysis.morphology.model.support.Noun;

import static com.alphasystem.app.morphologicalengine.conjugation.transformer.factory.noun.NounTransformerFactoryType.Type.FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY;
import static com.alphasystem.app.morphologicalengine.conjugation.transformer.factory.noun.NounTransformerFactoryType.Type.MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY;

/**
 * @author sali
 */
public interface NounRootBaseFactory {

    NounRootBase FORM_I_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_I_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_I_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_I_FEMININE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_I_MASCULINE_PASSIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_I_MASCULINE_PASSIVE_PARTICIPLE);
    NounRootBase FORM_I_FEMININE_PASSIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_I_FEMININE_PASSIVE_PARTICIPLE);
    NounRootBase FORM_I_CATEGORY_U_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_I_CATEGORY_U_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_I_CATEGORY_U_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_I_CATEGORY_U_FEMININE_ACTIVE_PARTICIPLE);

    NounRootBase FORM_II_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_II_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_II_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_II_FEMININE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_II_MASCULINE_PASSIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_II_MASCULINE_PASSIVE_PARTICIPLE);
    NounRootBase FORM_II_FEMININE_PASSIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_II_FEMININE_PASSIVE_PARTICIPLE);

    NounRootBase FORM_III_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_III_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_III_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_III_FEMININE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_III_MASCULINE_PASSIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_III_MASCULINE_PASSIVE_PARTICIPLE);
    NounRootBase FORM_III_FEMININE_PASSIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_III_FEMININE_PASSIVE_PARTICIPLE);

    NounRootBase FORM_IV_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_IV_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_IV_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_IV_FEMININE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_IV_MASCULINE_PASSIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_IV_MASCULINE_PASSIVE_PARTICIPLE);
    NounRootBase FORM_IV_FEMININE_PASSIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_IV_FEMININE_PASSIVE_PARTICIPLE);

    NounRootBase FORM_V_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_V_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_V_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_V_FEMININE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_V_MASCULINE_PASSIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_V_MASCULINE_PASSIVE_PARTICIPLE);
    NounRootBase FORM_V_FEMININE_PASSIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_V_FEMININE_PASSIVE_PARTICIPLE);

    NounRootBase FORM_VI_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VI_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_VI_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VI_FEMININE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_VI_MASCULINE_PASSIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VI_MASCULINE_PASSIVE_PARTICIPLE);
    NounRootBase FORM_VI_FEMININE_PASSIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VI_FEMININE_PASSIVE_PARTICIPLE);

    NounRootBase FORM_VII_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VII_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_VII_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VII_FEMININE_ACTIVE_PARTICIPLE);

    NounRootBase FORM_VIII_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VIII_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_VIII_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VIII_FEMININE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_VIII_MASCULINE_PASSIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VIII_MASCULINE_PASSIVE_PARTICIPLE);
    NounRootBase FORM_VIII_FEMININE_PASSIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_VIII_FEMININE_PASSIVE_PARTICIPLE);

    NounRootBase FORM_IX_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_IX_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_IX_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_IX_FEMININE_ACTIVE_PARTICIPLE);

    NounRootBase FORM_X_MASCULINE_ACTIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_X_MASCULINE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_X_FEMININE_ACTIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_X_FEMININE_ACTIVE_PARTICIPLE);
    NounRootBase FORM_X_MASCULINE_PASSIVE_PARTICIPLE = new NounRootBase(MASCULINE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_X_MASCULINE_PASSIVE_PARTICIPLE);
    NounRootBase FORM_X_FEMININE_PASSIVE_PARTICIPLE = new NounRootBase(FEMININE_SOUND_PLURAL_TRANSFORMER_FACTORY, Noun.FORM_X_FEMININE_PASSIVE_PARTICIPLE);
}
