package com.alphasystem.app.morphologicalengine.conjugation.model;

import com.alphasystem.morphologicalanalysis.morphology.model.support.Verb;

import static com.alphasystem.app.morphologicalengine.conjugation.transformer.factory.verb.VerbTransformerFactoryType.Type.FORBIDDING_TRANSFORMER_FACTORY;
import static com.alphasystem.app.morphologicalengine.conjugation.transformer.factory.verb.VerbTransformerFactoryType.Type.IMPERATIVE_TRANSFORMER_FACTORY;
import static com.alphasystem.app.morphologicalengine.conjugation.transformer.factory.verb.VerbTransformerFactoryType.Type.PAST_TENSE_TRANSFORMER_FACTORY;
import static com.alphasystem.app.morphologicalengine.conjugation.transformer.factory.verb.VerbTransformerFactoryType.Type.PRESENT_TENSE_TRANSFORMER_FACTORY;

/**
 * @author sali
 */
public interface VerbRootBaseFactory {

    VerbRootBase FORM_I_PAST_TENSE_V1 = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_I_PAST_TENSE_V1);
    VerbRootBase FORM_I_PAST_TENSE_V2 = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_I_PAST_TENSE_V2);
    VerbRootBase FORM_I_PAST_TENSE_V3 = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_I_PAST_TENSE_V3);

    VerbRootBase FORM_I_PRESENT_TENSE_V1 = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_I_PRESENT_TENSE_V1);
    VerbRootBase FORM_I_PRESENT_TENSE_V2 = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_I_PRESENT_TENSE_V2);
    VerbRootBase FORM_I_PRESENT_TENSE_V3 = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_I_PRESENT_TENSE_V3);

    VerbRootBase FORM_I_PAST_PASSIVE_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_I_PAST_PASSIVE_TENSE);
    VerbRootBase FORM_I_PRESENT_PASSIVE_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_I_PRESENT_PASSIVE_TENSE);

    VerbRootBase FORM_I_IMPERATIVE_V1 = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_I_IMPERATIVE_V1);
    VerbRootBase FORM_I_IMPERATIVE_V2 = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_I_IMPERATIVE_V2);
    VerbRootBase FORM_I_IMPERATIVE_V3 = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_I_IMPERATIVE_V3);
    VerbRootBase FORM_I_FORBIDDING_V1 = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_I_FORBIDDING_V1);
    VerbRootBase FORM_I_FORBIDDING_V2 = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_I_FORBIDDING_V2);
    VerbRootBase FORM_I_FORBIDDING_V3 = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_I_FORBIDDING_V3);

    VerbRootBase FORM_II_PAST_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_II_PAST_TENSE);
    VerbRootBase FORM_II_PRESENT_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_II_PRESENT_TENSE);
    VerbRootBase FORM_II_PAST_PASSIVE_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_II_PAST_PASSIVE_TENSE);
    VerbRootBase FORM_II_PRESENT_PASSIVE_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_II_PRESENT_PASSIVE_TENSE);
    VerbRootBase FORM_II_IMPERATIVE = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_II_IMPERATIVE);
    VerbRootBase FORM_II_FORBIDDING = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_II_FORBIDDING);

    VerbRootBase FORM_III_PAST_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_III_PAST_TENSE);
    VerbRootBase FORM_III_PRESENT_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_III_PRESENT_TENSE);
    VerbRootBase FORM_III_PAST_PASSIVE_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_III_PAST_PASSIVE_TENSE);
    VerbRootBase FORM_III_PRESENT_PASSIVE_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_III_PRESENT_PASSIVE_TENSE);
    VerbRootBase FORM_III_IMPERATIVE = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_III_IMPERATIVE);
    VerbRootBase FORM_III_FORBIDDING = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_III_FORBIDDING);

    VerbRootBase FORM_IV_PAST_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_IV_PAST_TENSE);
    VerbRootBase FORM_IV_PRESENT_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_IV_PRESENT_TENSE);
    VerbRootBase FORM_IV_PAST_PASSIVE_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_IV_PAST_PASSIVE_TENSE);
    VerbRootBase FORM_IV_PRESENT_PASSIVE_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_IV_PRESENT_PASSIVE_TENSE);
    VerbRootBase FORM_IV_IMPERATIVE = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_IV_IMPERATIVE);
    VerbRootBase FORM_IV_FORBIDDING = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_IV_FORBIDDING);

    VerbRootBase FORM_V_PAST_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_V_PAST_TENSE);
    VerbRootBase FORM_V_PRESENT_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_V_PRESENT_TENSE);
    VerbRootBase FORM_V_PAST_PASSIVE_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_V_PAST_PASSIVE_TENSE);
    VerbRootBase FORM_V_PRESENT_PASSIVE_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_V_PRESENT_PASSIVE_TENSE);
    VerbRootBase FORM_V_IMPERATIVE = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_V_IMPERATIVE);
    VerbRootBase FORM_V_FORBIDDING = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_V_FORBIDDING);

    VerbRootBase FORM_VI_PAST_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VI_PAST_TENSE);
    VerbRootBase FORM_VI_PRESENT_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VI_PRESENT_TENSE);
    VerbRootBase FORM_VI_PAST_PASSIVE_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VI_PAST_PASSIVE_TENSE);
    VerbRootBase FORM_VI_PRESENT_PASSIVE_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VI_PRESENT_PASSIVE_TENSE);
    VerbRootBase FORM_VI_IMPERATIVE = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_VI_IMPERATIVE);
    VerbRootBase FORM_VI_FORBIDDING = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_VI_FORBIDDING);

    VerbRootBase FORM_VII_PAST_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VII_PAST_TENSE);
    VerbRootBase FORM_VII_PRESENT_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VII_PRESENT_TENSE);
    VerbRootBase FORM_VII_IMPERATIVE = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_VII_IMPERATIVE);
    VerbRootBase FORM_VII_FORBIDDING = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_VII_FORBIDDING);

    VerbRootBase FORM_VIII_PAST_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VIII_PAST_TENSE);
    VerbRootBase FORM_VIII_PRESENT_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VIII_PRESENT_TENSE);
    VerbRootBase FORM_VIII_PAST_PASSIVE_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VIII_PAST_PASSIVE_TENSE);
    VerbRootBase FORM_VIII_PRESENT_PASSIVE_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_VIII_PRESENT_PASSIVE_TENSE);
    VerbRootBase FORM_VIII_IMPERATIVE = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_VIII_IMPERATIVE);
    VerbRootBase FORM_VIII_FORBIDDING = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_VIII_FORBIDDING);

    VerbRootBase FORM_IX_PAST_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_IX_PAST_TENSE);
    VerbRootBase FORM_IX_PRESENT_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_IX_PRESENT_TENSE);
    VerbRootBase FORM_IX_IMPERATIVE = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_IX_IMPERATIVE);
    VerbRootBase FORM_IX_FORBIDDING = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_IX_FORBIDDING);

    VerbRootBase FORM_X_PAST_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_X_PAST_TENSE);
    VerbRootBase FORM_X_PRESENT_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_X_PRESENT_TENSE);
    VerbRootBase FORM_X_PAST_PASSIVE_TENSE = new VerbRootBase(PAST_TENSE_TRANSFORMER_FACTORY, Verb.FORM_X_PAST_PASSIVE_TENSE);
    VerbRootBase FORM_X_PRESENT_PASSIVE_TENSE = new VerbRootBase(PRESENT_TENSE_TRANSFORMER_FACTORY, Verb.FORM_X_PRESENT_PASSIVE_TENSE);
    VerbRootBase FORM_X_IMPERATIVE = new VerbRootBase(IMPERATIVE_TRANSFORMER_FACTORY, Verb.FORM_X_IMPERATIVE);
    VerbRootBase FORM_X_FORBIDDING = new VerbRootBase(FORBIDDING_TRANSFORMER_FACTORY, Verb.FORM_X_FORBIDDING);
}
